import type { MetadataRoute } from "next";
import { siteUrl } from "@/lib/site";

// /robots.txt, generated by the app-router file convention. It 404'd until
// now, which leaves crawlers with no pointer to the sitemap.
//
// The whole site is open to crawlers — it's a pre-launch landing page whose
// entire job is to be found. The one exclusion is `/api/`, which serves JSON
// endpoints (the waitlist POST, the AI ops) that have nothing to offer a
// search index and shouldn't burn crawl budget.
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: "/api/",
    },
    // Must be absolute — the sitemap reference is one of the few places in
    // robots.txt where a relative path is not allowed.
    sitemap: new URL("/sitemap.xml", siteUrl).toString(),
  };
}
