import type { MetadataRoute } from "next";
import { siteUrl } from "@/lib/site";

// /sitemap.xml, generated by the app-router file convention. It 404'd until
// now, so the `Sitemap:` line in robots.txt had nothing to point at.
//
// Only the landing page is listed. `/trip` is deliberately left out: it's the
// Supabase-backed app shell, not marketing — client-rendered behind an auth
// session, so a crawler sees "Loading the trip…" and nothing else. Listing it
// would advertise an empty page as if it were content. It stays crawlable
// (robots.txt doesn't disallow it); we simply don't nominate it.
//
// No `lastModified`: a `new Date()` here would change on every build and make
// the sitemap churn without the page having changed, and a hand-maintained
// date would be a lie the moment someone edits the copy and forgets. Absent is
// honest, and crawlers treat it as a hint anyway.
export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: new URL("/", siteUrl).toString(),
      changeFrequency: "weekly",
      priority: 1,
    },
  ];
}
